### ISSUE TITLE
timestamps

### ISSUE THREAD

**Issue by bendichter** [DeepLabCut/DLC2NWB#1]
This looks really good! 

One issue I found is that the timestamps are integers, e.g. (1.0, 2.0, 3.0, ...). These should be the time in seconds with respect to the session start time. Does DLC track timing or does it simply go frame by frame without needing to know about the frame times? We may need to have an additional input argument to support this. We could input just a sampling rate, but I know that videos often have irregular sampling.

Another more minor thing is that if all the timestamps vectors are the same, we can do is create links between the timestamps so the values only need to be stored once in the file and the other timeseries object can point to it. It's easy to do this in PyNWB, but the syntax would be hard to guess. You do:

```python
timeseries1 = TimeSeries(...)
timeseries2 = TimeSeries(..., timestamps=timeseries1)
```

**Comment by AlexEMG** [comment]
By default we just store the frame index (thus integers). Most videos do not come with metadata that tells us the timing of each frame. We could allow people to pass the time series, if they have it?

**Comment by AlexEMG** [comment]
That said, for some videos, it works and we could generally store the timestamps in the DLC output file too and if the column exists, export it?

**Comment by AlexEMG** [comment]
Started @jeylau, what's left:
- [ ] testing it! 
- [ ] grouping timestamps as indicated above:

```
timeseries1 = TimeSeries(...)
timeseries2 = TimeSeries(..., timestamps=timeseries1)
```
