### ISSUE TITLE
Separate `PoseEstimation()` object from `NWBFile()` metadata?

### ISSUE THREAD

**Issue by CBroz1** [DeepLabCut/DLC2NWB#11]
I'm interested in using the [first half](https://github.com/DeepLabCut/DLC2NWB/blob/main/dlc2nwb/utils.py#L80-L155) of `convert_h5_to_nwb` to save with different metadata from DataJoint Elements.

Would you be interested in a PR that separated out the pieces that generated `PoseEstimation()` object?

**Comment by CodyCBakerPhD** [comment]
@CBroz1 Check out https://github.com/DeepLabCut/DLC2NWB/pull/10 for one attempt at doing something like this but need traction upstream to make it happen

CC: @h-mayorquin, point person on the effort there

**Comment by CBroz1** [comment]
Ah - missed that. Yes, I think `_write_pes_to_nwbfile` from that PR would do what I needed. I'll keep an eye on the progress there.
