### ISSUE TITLE
Having a new release to include append nwbfile mode

### ISSUE THREAD

**Issue by h-mayorquin** [DeepLabCut/DLC2NWB#13]
After you have merged https://github.com/DeepLabCut/DLC2NWB/pull/10 we were wondering if you could do a new release. That would allow us to indicate the users that they can use this new feature by using  `pip install dlc2nwb` instead of telling them to install the dev branch from github. 

Let us know if there is anything that we can help you to make this happen.

**Comment by AlexEMG** [comment]
Done, thanks for the contribution!
