### ISSUE TITLE
including skeleton

### ISSUE THREAD

**Issue by bendichter** [DeepLabCut/DLC2NWB#3]
ndx-pose has a place for "edges", which I think maps to "skeleton" in DLC. However, the example config.yml does not contain skeleton information and the converter does not handle skeleton info. Including this information would allow us to provide much better visualizations of DLC output in NWB Widgets.

**Comment by AlexEMG** [comment]
Depends on the philosophy. The most extreme case is having all metadata to document how the data was created; the minimalist version could be just the network name (scorer name as it is already included)

What are the essential values to store to understand the dataset and the process by which the dataset was produced?

- training/test dataset files 
- Frames and labeled coordinates on frames
- Config settings
- Network architecture and training parameters
- ImageNet pretrained names, e.g., Resnet-50 https://github.com/DeepLabCut/DeepLabCut/blob/master/deeplabcut/pose_estimation_tensorflow/models/pretrained/pretrained_model_urls.yaml
- Model Zoo
- Version of DLC code
- settings for augmentation pipeline 
- settings for inference code (e.g. thresholds, graph, etc.)
- one could even put the log files (yaml, tensor flow output, …)

For a given project, this metadata is likely going to be identical and could be put in a central NWB project file? On the other hand, the metadata is relatively small to store and could go with each video's output.

**Comment by AlexEMG** [comment]
Opened this issue more towards general metadata: https://github.com/DeepLabCut/DLC2NWB/issues

**Comment by AlexEMG** [comment]
The skeleton is now in!
