### ISSUE TITLE
Installation and release

### ISSUE THREAD

**Issue by AlexEMG** [DeepLabCut/DLC2NWB#5]
Once we are happy with this converter, we will integrate the functionality in DLC.

- [x] put [ndx-pose](https://github.com/rly/ndx-pose) on pypi
- [x] put DLC2NWB code on pypi --> [voila](https://pypi.org/project/dlc2nwb/)
- [x] allow exporting from DeepLabCut, see here: https://github.com/DeepLabCut/DeepLabCut/tree/nwb

**Comment by AlexEMG** [comment]
We will also pick up speed again for #1 #4

**Comment by bendichter** [comment]
@AlexEMG would it be possible to resolve #3 first? This feature is currently supported by ndx-pose, and I want to make sure it fits with DLC before publishing.

**Comment by AlexEMG** [comment]
Ok, #3 is done!
